// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MusicCat.Musiclibrary.Count;
using MusicCat.Musiclibrary.Reload;
using MusicCat.Musiclibrary.Verify;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MusicCat.Musiclibrary
{
    /// <summary>
    /// Builds and executes requests for operations under \musiclibrary
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MusiclibraryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The count property</summary>
        public global::MusicCat.Musiclibrary.Count.CountRequestBuilder Count
        {
            get => new global::MusicCat.Musiclibrary.Count.CountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reload property</summary>
        public global::MusicCat.Musiclibrary.Reload.ReloadRequestBuilder Reload
        {
            get => new global::MusicCat.Musiclibrary.Reload.ReloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The verify property</summary>
        public global::MusicCat.Musiclibrary.Verify.VerifyRequestBuilder Verify
        {
            get => new global::MusicCat.Musiclibrary.Verify.VerifyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MusicCat.Musiclibrary.MusiclibraryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MusiclibraryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/musiclibrary", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MusicCat.Musiclibrary.MusiclibraryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MusiclibraryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/musiclibrary", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
