using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TPP.ArgsParsing.Types;

namespace TPP.ArgsParsing.TypeParsers
{
    public class FormParser : IArgumentParser<Form>
    {
        /// <summary>
        /// Keys and values are in the format: lowercase unspaced name | Capitalized display name.
        /// </summary>
        private static readonly Dictionary<string, string> Forms = new Dictionary<string, string>
        {
            #region common forms
            ["alolan"] = "Alolan",
            ["alola"] = "Alolan",
            ["glarian"] = "Galarian",
            ["galar"] = "Galarian",
            ["hisuian"] = "Hisuian", //pokemon legends: arceus 
            ["hisui"] = "Hisuan",

            ["mega"] = "Mega",
            ["dynamax"] = "Dyanamax",
            ["gigantamax"] = "Gigantamax",
            ["normal"] = "Normal",

            ["red"] = "Red",
            ["red-stripe"] = "Red", //basculin
            ["redstripe"] = "Red",
            ["redflower"] = "Red", //Flabébé, Floette, and Florges
            ["redcore"] = "Red", //minior
            ["blue"] = "Blue",
            ["blue-stripe"] = "Blue",
            ["bluestripe"] = "Blue",
            ["blueflower"] = "Blue",
            ["bluecore"] = "Blue",
            ["white"] = "White",
            ["whiteflower"] = "White",
            ["black"] = "Black",
            ["orange"] = "Orange",
            ["orangeflower"] = "Orange",
            ["orangecore"] = "Orange",
            ["yellow"] = "Yellow",
            ["yellowflower"] = "Yellow",
            ["yellowcore"] = "Yellow",
            ["green"] = "Green",
            ["greencore"] = "Green",
            ["indigocore"] = "Indigo",
            ["indigo"] = "Indigo",
            ["violet"] = "Violet",
            ["violetcore"] = "Violet",
            #endregion

            #region pokemon specific forms
            ["primal"] = "Primal", //Kyogre, Groudon  
            ["fire"] = "Fire", //Arceus, Silvally
            ["water"] = "Water",
            ["electric"] = "Electric",
            ["grass"] = "Grass",
            ["ice"] = "Ice",
            ["fighting"] = "fighting",
            ["poison"] = "Poison",
            ["ground"] = "Ground",
            ["psychic"] = "Psychic",
            ["flying"] = "Flying",
            ["bug"] = "Bug",
            ["rock"] = "Rock",
            ["ghost"] = "Ghost",
            ["dragon"] = "Dragon",
            ["dark"] = "Dark",
            ["steel"] = "Steel",
            ["fairy"] = "Fairy",
            ["???"] = "???",
            //["normal"] = "Normal", redundant since it is defined above, but left here to show that there is completeness across types
            ["cosplay"] = "Cosplay", //pikachu
            ["rockstar"] = "Rock Star",
            ["belle"] = "Belle",
            ["popstar"] = "Pop Star",
            ["phd"] = "PHD",
            ["dr"] = "PHD",
            ["libre"] = "Libre",
            ["originalcap"] = "Original Cap",
            ["hoenncap"] = "Hoenn Cap",
            ["sinnohcap"] = "Sinnoh Cap",
            ["unovacap"] = "Unova Cap",
            ["kaloscap"] = "Kalos Cap",
            ["alolacap"] = "Alola Cap",
            ["partnercap"] = "Partner Cap",
            ["worldcap"] = "World Cap",
            ["spiky-eared"] = "Spiky-Eared", //pichu
            ["spikyeared"] = "Spiky-Eared",
            ["a"] = "A", //unown
            ["b"] = "B",
            ["c"] = "C",
            ["d"] = "D",
            ["e"] = "E",
            ["f"] = "F",
            ["g"] = "G",
            ["h"] = "H",
            ["i"] = "I",
            ["j"] = "J",
            ["k"] = "K",
            ["l"] = "L",
            ["m"] = "M",
            ["n"] = "N",
            ["o"] = "O",
            ["p"] = "P",
            ["q"] = "Q",
            ["r"] = "R",
            ["s"] = "S",
            ["t"] = "T",
            ["u"] = "U",
            ["v"] = "V",
            ["w"] = "W",
            ["x"] = "X",
            ["y"] = "Y",
            ["z"] = "Z",
            ["?"] = "?",
            ["!"] = "!",
            ["sunny"] = "Sunny", //castform
            ["rainy"] = "Rainy",
            ["rain"] = "Rainy",
            ["snowy"] = "Snowy",
            ["snow"] = "Snowy",
            ["attack"] = "Attack", //deoxys 
            ["defence"] = "Defence",
            ["speed"] = "Speed",
            ["plantcloak"] = "Plant Cloak", //burmy & wormadam
            ["plant"] = "Plant Cloak",
            ["sandycloak"] = "Sandy Cloak",
            ["sandcloak"] = "Sandy Cloak",
            ["sand"] = "Sandy Cloak",
            ["trashcloak"] = "Trash Cloak",
            ["trash"] = "Trash Cloak",
            ["overcast"] = "Overcast", //cherrim
            ["sunshine"] = "Sunshine",
            ["westsea"] = "West Sea", //shelos & gastrodon
            ["west"] = "West Sea",
            ["eastsea"] = "East Sea",
            ["east"] = "East Sea",
            ["heat"] = "Heat", //rotom
            ["wash"] = "Wash",
            ["frost"] = "Frost",
            ["fan"] = "Fan",
            ["mow"] = "Mow",
            ["pokedex"] = "Pokédex",
            ["phone"] = "phone",
            ["origin"] = "Origin", //giritina
            ["land"] = "Land", //shaymin
            ["sky"] = "Sky",
            ["standard"] = "Standard", //darmanitan
            ["zen"] = "Zen",
            ["galarianstandard"] = "Galarian Standard",
            ["galarstandard"] = "Galarian Standard",
            ["galarianzen"] = "Galarian Zen",
            ["galarzen"] = "Galarian Zen",
            ["spring"] = "Spring", //deerling & sawsbuck
            ["summer"] = "Summer",
            ["autumn"] = "Autumn",
            ["fall"] = "Autumn",
            ["winter"] = "Winter",
            ["incarnate"] = "Incarnate", //tornadus, thundurus, landorus
            ["therian"] = "Therian",
            ["ordinary"] = "Ordinary", //keldeo
            ["resolute"] = "Resoulte",
            ["aria"] = "Aria", //Meloetta
            ["pirouette"] = "Pirouette",
            ["shockdrive"] = "Shock Drive", //genesect
            ["shock"] = "Shock Drive",
            ["burndrive"] = "Burn Drive",
            ["burn"] = "Burn Drive",
            ["chilldrive"] = "Chill Drive",
            ["chill"] = "Chill Drive",
            ["dousedrive"] = "Douse Drive",
            ["douse"] = "Douse Drive",
            ["ash-greninja"] = "Ash-Greninja", //greninja
            ["ashgreninja"] = "Ash-Greninja",
            ["ash"] = "Ash-Greninja",
            ["archipelago"] = "Archipelago", //vivillon
            ["continental"] = "Continental",
            ["elegant"] = "Elegant",
            ["garden"] = "Garden",
            ["highplains"] = "High Plains",
            ["icysnow"] = "Icy Snow",
            ["icy"] = "Icy Snow",
            ["jungle"] = "Jungle",
            ["marine"] = "Marine",
            ["meadow"] = "Meadow",
            ["modern"] = "Modern",
            ["monsoon"] = "Monsoon",
            ["ocean"] = "Ocean",
            ["polar"] = "Polar",
            ["river"] = "River",
            ["sandstorm"] = "Sandstorm",
            ["savanna"] = "Savanna",
            ["sun"] = "Sun",
            ["tundra"] = "Tundra",
            ["pokeball"] = "Poké Ball",
            ["fancy"] = "Fancy",
            ["natural"] = "Normal", //furfou
            ["hearttrim"] = "Heart Trim",
            ["heart"] = "Heart Trim",
            ["startrim"] = "Star Trim",
            ["diamondtrim"] = "Diamond Trim",
            ["debutantetrim"] = "Debutante Trim",
            ["debutante"] = "Debutante Trim",
            ["matrontrim"] = "Matron Trim",
            ["matron"] = "Matron Trim",
            ["dandytrim"] = "Dandy Trim",
            ["lareinetrim"] = "La Reine Trim",
            ["lareine"] = "La Reine Trim",
            ["kabukitrim"] = "Kabuki Trim",
            ["kabuki"] = "Kabuki Trim",
            ["pharohtrim"] = "Pharoh Trim",
            ["pharoh"] = "Pharoh Trim",
            ["shield"] = "Shield", //aegislash, zamazenta
            ["crownedshield"] = "Shield", //zamazenta
            ["blade"] = "Blade", //aegislash
            ["sword"] = "Sword", //zacian
            ["crownedsword"] = "Sword",
            ["heroofmanybattles"] = "Hero of Many Battles", //zacian & zamazenta
            ["hero"] = "Hero of Many Battles",
            ["small"] = "Small", //pumpkaboo & gourgeist
            ["average"] = "Average",
            ["large"] = "Large",
            ["super"] = "Super",
            ["neutralmode"] = "Neutral Mode", //xerneas
            ["neutral"] = "Neutral Mode",
            ["activemode"] = "Active Mode",
            ["active"] = "Active Mode",
            ["cell"] = "Cell", //zygarde
            ["core"] = "Core",
            ["10%"] = "10%",
            ["10percent"] = "10%",
            ["50%"] = "50%",
            ["50percent"] = "50%",
            ["complete"] = "Complete",
            ["confined"] = "Confined", //hoopa
            ["unbound"] = "Unbound",
            ["bailestyle"] = "Baile Style", //oricorio
            ["baile"] = "Baile Style",
            ["pom-pomstyle"] = "Pom-Pom Style",
            ["pompomstyle"] = "Pom-Pom Style",
            ["pompom"] = "Pom-Pom Style",
            ["pa'ustyle"] = "Pa'u Style",
            ["paustyle"] = "Pa'u Style",
            ["pau"] = "Pa'u Style",
            ["sensustyle"] = "Sensu Style",
            ["sensu"] = "Sensu Style",
            ["midday"] = "Midday", //lycanroc
            ["midnight"] = "Midnight",
            ["dusk"] = "Dusk",
            ["solo"] = "Solo", //wishiwashi
            ["school"] = "School",
            ["meteor"] = "Meteor", //minor (color forms above)
            ["disguised"] = "Disguised", //mimikyu
            ["busted"] = "Busted",
            ["duskmane"] = "Dusk", //necrozma
            ["dawn"] = "Dawn",
            ["dawnwings"] = "Dawn",
            ["ultra"] = "Ultra",
            ["originalcolor"] = "Original Color", //magearna
            ["gulping"] = "Gulping", //cramorant
            ["gorging"] = "Gorging",
            ["amped"] = "Amped", //toxtricity
            ["low-key"] = "Low Key",
            ["lowkey"] = "Low Key",
            ["phony"] = "Phony", //sinistea & polteageist
            ["antique"] = "Antique",
            ["strawberryvanilla"] = "Strawberry Vanilla", //alcremie...
            ["blueberryvanilla"] = "Blueberry Vanilla",
            ["lovevanilla"] = "Love Vanilla",
            ["starvanilla"] = "Star Vanilla",
            ["clovervanilla"] = "Clover Vanilla",
            ["flowervanilla"] = "Flower Vanilla",
            ["ribbonvanilla"] = "Ribbon Vanilla",
            ["strawberryruby"] = "Strawberry Ruby",
            ["blueberryruby"] = "Blueberry Ruby",
            ["loveruby"] = "Love Ruby",
            ["starruby"] = "Star Ruby",
            ["cloverruby"] = "Clover Ruby",
            ["flowerruby"] = "Flower Ruby",
            ["ribbonruby"] = "Ribbon Ruby",
            ["strawberrymatcha"] = "Strawberry Matcha",
            ["blueberrymatcha"] = "Blueberry Matcha",
            ["lovematcha"] = "Love Matcha",
            ["starmatcha"] = "Star Matcha",
            ["clovermatcha"] = "Clover Matcha",
            ["flowermatcha"] = "Flower Matcha",
            ["ribbonmatcha"] = "Ribbon Matcha",
            ["strawberrymint"] = "Strawberry Mint",
            ["blueberrymint"] = "Blueberry Mint",
            ["lovemint"] = "Love Mint",
            ["starmint"] = "Star Mint",
            ["clovermint"] = "Clover Mint",
            ["flowermint"] = "Flower Mint",
            ["ribbonmint"] = "Ribbon Mint",
            ["strawberrylemon"] = "Strawberry Lemon",
            ["blueberrylemon"] = "Blueberry Lemon",
            ["lovelemon"] = "Love Lemon",
            ["starlemon"] = "Star Lemon",
            ["cloverlemon"] = "Clover Lemon",
            ["flowerlemon"] = "Flower Lemon",
            ["ribbonlemon"] = "Ribbon Lemon",
            ["strawberrysalted"] = "Strawberry Salted",
            ["blueberrysalted"] = "Blueberry Salted",
            ["lovesalted"] = "Love Salted",
            ["starsalted"] = "Star Salted",
            ["cloversalted"] = "Clover Salted",
            ["flowersalted"] = "Flower Salted",
            ["ribbonsalted"] = "Ribbon Salted",
            ["strawberryruby"] = "Strawberry Ruby",
            ["blueberryruby"] = "Blueberry Ruby",
            ["loveruby"] = "Love Ruby",
            ["starruby"] = "Star Ruby",
            ["cloverruby"] = "Clover Ruby",
            ["flowerruby"] = "Flower Ruby",
            ["ribbonruby"] = "Ribbon Ruby",
            ["strawberrycaramel"] = "Strawberry Caramel",
            ["blueberrycaramel"] = "Blueberry Caramel",
            ["lovecaramel"] = "Love Caramel",
            ["starcaramel"] = "Star Caramel",
            ["clovercaramel"] = "Clover Caramel",
            ["flowercaramel"] = "Flower Caramel",
            ["ribboncaramel"] = "Ribbon Caramel",
            ["strawberryrainbow"] = "Strawberry Rainbow",
            ["blueberryrainbow"] = "Blueberry Rainbow",
            ["loverainbow"] = "Love Rainbow",
            ["starrainbow"] = "Star Rainbow",
            ["cloverrainbow"] = "Clover Rainbow",
            ["flowerrainbow"] = "Flower Rainbow",
            ["ribbonrainbow"] = "Ribbon Rainbow",
            ["iceface"] = "Ice Face", //eiscue
            ["noiceface"] = "Noice Face",
            ["fullbelly"] = "Full Belly", //morepko
            ["full"] = "Full Belly",
            ["hangry"] = "Hangry",
            ["eternamax"] = "Eternamax", //eternatus
            ["singlestrike"] = "Single Strike", //urshifu
            ["single"] = "Single Strike",
            ["rapidstrike"] = "Rapid Strike",
            ["rapid"] = "Rapid Strike",
            ["dada"] = "Dada", //zarude
            ["icerider"] = "Ice Rider", //calyrex
            ["shadowrider"] = "Shadow Rider",
            ["overdrive"] = "Overdrive", //reshiram, zerkom, kyurem
            ["radientsun"] = "Sun", //solgaleo
            ["fullmoon"] = "Moon", //lunala
            ["moon"] = "Moon",
            ["zenith"] = "Zenith", //marshadow
            #endregion
            // compiled from https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_with_form_differences on 11/9/21
        };
        public Task<ArgsParseResult<Form>> Parse(IImmutableList<string> args, Type[] genericTypes)
        {
            string toValidate = args[0].ToLower();
            ArgsParseResult<Form> result;
            if (Forms.TryGetValue(toValidate, out string? formName))
                result = ArgsParseResult<Form>.Success(new Form(formName), args.Skip(1).ToImmutableList());
            else
                result = ArgsParseResult<Form>.Failure("Invalid form name");
            return Task.FromResult(result);
        }
    }
}
